#define MAX_POINT_LIGHTS 100

#define MAX_SPOT_LIGHTS 10

#define MAX_SPOT_SHADOWS 10

//88#define MAX_SPOT_LIGHTS 10
#define MAX_POINT_SHADOWS 5

#define MAX_BONES 200

#define LIGHT_RADIUS 30.0f

#define LIGHT_SPOT_MULTIPLIER 1.7f
#define LIGHT_POINT_MULTIPLIER 3.0f

#define MAX_VIEW_DISTANCE 130.0f
#define MAX_LIGHT_DISTANCE 290.0f

#define GLOW_BLUR 8
