#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class Grid;
                ref class TextBlock;
                ref class StackPanel;
                ref class CheckBox;
                ref class ListView;
                ref class Slider;
                ref class Button;
                ref class Border;
                ref class Image;
                ref class Viewbox;
            }
        }
    }
}

namespace Game
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ swapChainPanel;
        private: ::Windows::UI::Xaml::Controls::Grid^ left_buttons;
        private: ::Windows::UI::Xaml::Controls::Grid^ right_buttons;
        private: ::Windows::UI::Xaml::Controls::Grid^ char_left_buttons;
        private: ::Windows::UI::Xaml::Controls::Grid^ char_right_buttons;
        private: ::Windows::UI::Xaml::Controls::Grid^ game_hud;
        private: ::Windows::UI::Xaml::Controls::Grid^ game_right_buttons;
        private: ::Windows::UI::Xaml::Controls::Grid^ right_editor;
        private: ::Windows::UI::Xaml::Controls::Grid^ options_hud;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ felt_tex;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dice_tex;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dice_num;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ right_selector;
        private: ::Windows::UI::Xaml::Controls::Grid^ right_cols;
        private: ::Windows::UI::Xaml::Controls::Grid^ right_chooser;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ phy_but;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ rand_but;
        private: ::Windows::UI::Xaml::Controls::ListView^ items_list;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ bx;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ bz;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ba;
        private: ::Windows::UI::Xaml::Controls::Slider^ slider1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ protate;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderrx;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderry;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderrz;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ptext;
        private: ::Windows::UI::Xaml::Controls::Slider^ blend_num;
        private: ::Windows::UI::Xaml::Controls::Button^ clearpaths;
        private: ::Windows::UI::Xaml::Controls::Button^ newpath;
        private: ::Windows::UI::Xaml::Controls::Button^ bakepath;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ loop_but;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ dip_but;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderrr;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderrg;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderrb;
        private: ::Windows::UI::Xaml::Controls::Border^ col_view;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ cx;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ cz;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ca;
        private: ::Windows::UI::Xaml::Controls::Slider^ tval1;
        private: ::Windows::UI::Xaml::Controls::Slider^ tval2;
        private: ::Windows::UI::Xaml::Controls::Slider^ tval3;
        private: ::Windows::UI::Xaml::Controls::Slider^ tval4;
        private: ::Windows::UI::Xaml::Controls::Button^ genter;
        private: ::Windows::UI::Xaml::Controls::Slider^ sambr;
        private: ::Windows::UI::Xaml::Controls::Slider^ sambg;
        private: ::Windows::UI::Xaml::Controls::Slider^ sambb;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffr;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffg;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffb;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffx;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffy;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffz;
        private: ::Windows::UI::Xaml::Controls::Slider^ sspecr;
        private: ::Windows::UI::Xaml::Controls::Slider^ sspecg;
        private: ::Windows::UI::Xaml::Controls::Slider^ sspecb;
        private: ::Windows::UI::Xaml::Controls::Slider^ sspecpow;
        private: ::Windows::UI::Xaml::Controls::Image^ in_car;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ total_box;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dice_total;
        private: ::Windows::UI::Xaml::Controls::Image^ attack_grab;
        private: ::Windows::UI::Xaml::Controls::Image^ button_jump;
        private: ::Windows::UI::Xaml::Controls::Image^ move_pad;
        private: ::Windows::UI::Xaml::Controls::Image^ button_right;
        private: ::Windows::UI::Xaml::Controls::Image^ button_left;
        private: ::Windows::UI::Xaml::Controls::Image^ button_carsteer;
        private: ::Windows::UI::Xaml::Controls::Image^ button_grab;
        private: ::Windows::UI::Xaml::Controls::Image^ button_up;
        private: ::Windows::UI::Xaml::Controls::Image^ button_down;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ fps;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ timer;
        private: ::Windows::UI::Xaml::Controls::Image^ button_menu;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ level;
    };
}

