//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "DirectXPage.xaml.h"

void ::Game::DirectXPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///DirectXPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Game::DirectXPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->swapChainPanel = safe_cast<::Windows::UI::Xaml::Controls::SwapChainPanel^>(__target);
        }
        break;
    case 3:
        {
            this->left_buttons = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 4:
        {
            this->right_buttons = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 5:
        {
            this->char_left_buttons = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 6:
        {
            this->char_right_buttons = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 7:
        {
            this->game_hud = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 8:
        {
            this->game_right_buttons = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 9:
        {
            this->right_editor = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 10:
        {
            this->options_hud = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 11:
        {
            ::Windows::UI::Xaml::Controls::Image^ element11 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(element11))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Button_Click_fl);
        }
        break;
    case 12:
        {
            this->felt_tex = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 13:
        {
            ::Windows::UI::Xaml::Controls::Image^ element13 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(element13))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Button_Click_fr);
        }
        break;
    case 14:
        {
            ::Windows::UI::Xaml::Controls::Image^ element14 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(element14))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Button_Click_cl);
        }
        break;
    case 15:
        {
            this->dice_tex = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 16:
        {
            ::Windows::UI::Xaml::Controls::Image^ element16 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(element16))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Button_Click_cr);
        }
        break;
    case 17:
        {
            ::Windows::UI::Xaml::Controls::Image^ element17 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(element17))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Button_Click_dl);
        }
        break;
    case 18:
        {
            this->dice_num = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 19:
        {
            ::Windows::UI::Xaml::Controls::Image^ element19 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(element19))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Button_Click_dr);
        }
        break;
    case 20:
        {
            this->right_selector = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 21:
        {
            this->right_cols = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 22:
        {
            this->right_chooser = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 23:
        {
            this->phy_but = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->phy_but))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::phy_check);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->phy_but))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::phy_uncheck);
        }
        break;
    case 24:
        {
            this->rand_but = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->rand_but))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::rand_check);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->rand_but))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::rand_uncheck);
        }
        break;
    case 25:
        {
            this->items_list = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ListView^>(this->items_list))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&DirectXPage::items_list_SelectionChanged);
        }
        break;
    case 27:
        {
            this->bx = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 28:
        {
            this->bz = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 29:
        {
            this->ba = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 30:
        {
            this->slider1 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->slider1))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::slider_ValueChanged);
        }
        break;
    case 31:
        {
            this->protate = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 32:
        {
            this->sliderrx = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderrx))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sliderrx_ValueChanged);
        }
        break;
    case 33:
        {
            this->sliderry = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderry))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sliderry_ValueChanged);
        }
        break;
    case 34:
        {
            this->sliderrz = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderrz))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sliderrz_ValueChanged);
        }
        break;
    case 35:
        {
            this->ptext = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 36:
        {
            this->blend_num = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->blend_num))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::blend_num_ValueChanged);
        }
        break;
    case 37:
        {
            this->clearpaths = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->clearpaths))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::clear_paths_click);
        }
        break;
    case 38:
        {
            this->newpath = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->newpath))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::path_new_click);
        }
        break;
    case 39:
        {
            this->bakepath = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bakepath))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::path_bake_click);
        }
        break;
    case 40:
        {
            this->loop_but = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->loop_but))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::loop_check);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->loop_but))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::loop_uncheck);
        }
        break;
    case 41:
        {
            this->dip_but = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->dip_but))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::dip_check);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->dip_but))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::dip_uncheck);
        }
        break;
    case 42:
        {
            this->sliderrr = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderrr))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sliderrr_ValueChanged);
        }
        break;
    case 43:
        {
            this->sliderrg = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderrg))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sliderrg_ValueChanged);
        }
        break;
    case 44:
        {
            this->sliderrb = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderrb))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sliderrb_ValueChanged);
        }
        break;
    case 45:
        {
            this->col_view = safe_cast<::Windows::UI::Xaml::Controls::Border^>(__target);
        }
        break;
    case 46:
        {
            this->cx = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 47:
        {
            this->cz = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 48:
        {
            this->ca = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 49:
        {
            this->tval1 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->tval1))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::tval1_ValueChanged);
        }
        break;
    case 50:
        {
            this->tval2 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->tval2))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::tval2_ValueChanged);
        }
        break;
    case 51:
        {
            this->tval3 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->tval3))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::tval3_ValueChanged);
        }
        break;
    case 52:
        {
            this->tval4 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->tval4))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::tval4_ValueChanged);
        }
        break;
    case 53:
        {
            this->genter = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->genter))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::gen_ter_click);
        }
        break;
    case 54:
        {
            this->sambr = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sambr))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sambr_ValueChanged);
        }
        break;
    case 55:
        {
            this->sambg = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sambg))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sambg_ValueChanged);
        }
        break;
    case 56:
        {
            this->sambb = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sambb))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sambb_ValueChanged);
        }
        break;
    case 57:
        {
            this->sdiffr = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sdiffr))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sdiffr_ValueChanged);
        }
        break;
    case 58:
        {
            this->sdiffg = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sdiffg))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sdiffg_ValueChanged);
        }
        break;
    case 59:
        {
            this->sdiffb = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sdiffb))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sdiffb_ValueChanged);
        }
        break;
    case 60:
        {
            this->sdiffx = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sdiffx))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sdiffx_ValueChanged);
        }
        break;
    case 61:
        {
            this->sdiffy = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sdiffy))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sdiffy_ValueChanged);
        }
        break;
    case 62:
        {
            this->sdiffz = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sdiffz))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sdiffz_ValueChanged);
        }
        break;
    case 63:
        {
            this->sspecr = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sspecr))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sspecr_ValueChanged);
        }
        break;
    case 64:
        {
            this->sspecg = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sspecg))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sspecg_ValueChanged);
        }
        break;
    case 65:
        {
            this->sspecb = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sspecb))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sspecb_ValueChanged);
        }
        break;
    case 66:
        {
            this->sspecpow = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sspecpow))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::sspecpow_ValueChanged);
        }
        break;
    case 67:
        {
            ::Windows::UI::Xaml::Controls::Button^ element67 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element67))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::col_reset_click);
        }
        break;
    case 68:
        {
            ::Windows::UI::Xaml::Controls::Button^ element68 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element68))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::col_save_click);
        }
        break;
    case 69:
        {
            ::Windows::UI::Xaml::Controls::Button^ element69 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element69))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::Button_Click);
        }
        break;
    case 70:
        {
            ::Windows::UI::Xaml::Controls::Button^ element70 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element70))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::Button_Click_1);
        }
        break;
    case 71:
        {
            this->in_car = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->in_car))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::in_car_PointerPressed);
        }
        break;
    case 72:
        {
            this->total_box = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(this->total_box))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_right_PointerReleased);
        }
        break;
    case 73:
        {
            this->dice_total = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 74:
        {
            this->attack_grab = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->attack_grab))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::attack_grab_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->attack_grab))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::attackn_grab_PointerReleased);
        }
        break;
    case 75:
        {
            this->button_jump = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_jump))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_jump_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_jump))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_jump_PointerReleased);
        }
        break;
    case 76:
        {
            this->move_pad = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->move_pad))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_move_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->move_pad))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_move_PointerReleased);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->move_pad))->PointerMoved += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_move_PointerMoved);
        }
        break;
    case 77:
        {
            this->button_right = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_right))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_right_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_right))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_right_PointerReleased);
        }
        break;
    case 78:
        {
            this->button_left = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_left))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_left_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_left))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_left_PointerReleased);
        }
        break;
    case 79:
        {
            this->button_carsteer = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_carsteer))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_carsteer_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_carsteer))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_carsteer_PointerReleased);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_carsteer))->PointerMoved += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_carsteer_PointerMove);
        }
        break;
    case 80:
        {
            this->button_grab = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_grab))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_grab_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_grab))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_grab_PointerReleased);
        }
        break;
    case 81:
        {
            this->button_up = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_up))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_up_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_up))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_up_PointerReleased);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_up))->PointerMoved += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_up_PointerMoved);
        }
        break;
    case 82:
        {
            this->button_down = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_down))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_down_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_down))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_down_PointerReleased);
        }
        break;
    case 83:
        {
            this->fps = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 84:
        {
            this->timer = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 85:
        {
            this->button_menu = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->button_menu))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Game::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::button_menu_PointerPressed);
        }
        break;
    case 86:
        {
            this->level = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Game::DirectXPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


